<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_USER NAME OR EMAIL_RequestFormcaptcha</name>
   <tag></tag>
   <elementGuidId>7b4f4c94-3498-455a-83bc-ddd4387b53e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='requestform-captcha']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#requestform-captcha</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd4a37c1-584d-4e03-a97c-c86e46b3158b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c211e2a7-7217-4253-bd0e-dfa602faa742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>requestform-captcha</value>
      <webElementGuid>0343047e-d474-466a-9e91-5710e5ad2599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input100captcha</value>
      <webElementGuid>f1f755ab-51c3-4c6f-ad35-55b3844f7e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RequestForm[captcha]</value>
      <webElementGuid>bde1531e-8885-442c-b303-b32726d0c9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert Captcha</value>
      <webElementGuid>8ff94d60-e472-4a92-bce2-f030652e67d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ecd444d4-a5c4-48ac-a9a8-1136f38cd6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requestform-captcha&quot;)</value>
      <webElementGuid>8fbe7ec5-f001-4693-a21a-22ab1090a2fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='requestform-captcha']</value>
      <webElementGuid>47860a4e-4c88-4f89-8e34-533cf18c737c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p0']/div/div/input</value>
      <webElementGuid>360ae8fb-ef51-462f-9670-9c64f4012c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>6f67cb77-ec6e-4061-a0c6-297d87eb72ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'requestform-captcha' and @name = 'RequestForm[captcha]' and @placeholder = 'Insert Captcha']</value>
      <webElementGuid>4d97a7ae-b5b8-41ff-a90b-beb5240486d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
